name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: 修改数据库密码
      run: sed -i.old s/XXXX/${{secrets.PASSWORD}}/g src/main/resources/application.properties

    - name: 添加服务器公钥
      run: mkdir -p ~/.ssh && ls ~/.ssh && touch  ~/.ssh/known_hosts && cat  ~/.ssh/known_hosts && echo "weizeling.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMPZOsVAPef9o8KFiZ/4inK65ob2leXZL32VgI7KNp5g" > ~/.ssh/known_hosts

    - name: 配置本地环境
      run: sudo apt install sshpass && mkdir -p /tmp/mkstemp && ssh-keygen -R ${{secrets.HOST}}

    - name: maven编译
      run: mvn -B package --file pom.xml

    - name: 上传到服务器
      run: sshpass -p ${{secrets.SERVERPASSWORD}} scp ${{secrets.USERNAME}}@${{secrets.HOST}}:~/playground/target/ target/website-0.0.1-SNAPSHOT.jar

    - name: 重启程序
      run: sshpass -p ${{secrets.SERVERPASSWORD}} ssh ${{secrets.USERNAME}}@${{secrets.HOST}} 'bash -s' < echo 'sh ~/playground/start.sh'

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
