name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: 修改数据库密码
      run: sed -i.old s/XXXX/${{secrets.PASSWORD}}/g src/main/resources/application.properties

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: 上传到服务器
      run: sudo apt install sshpass && ssh-keygen -R weizeling.com && sshpass -p ${{secrets.SERVERPASSWORD}} scp ${{secrets.USERNAME}}@${{secrets.HOST}}.com:/playground/target/ target/website-0.0.1-SNAPSHOT.jar

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
